// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlcwexdebphvjbassbdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsY3dleGRlYnBodmpiYXNzYmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNTkwNzgsImV4cCI6MjA1NjgzNTA3OH0.xLa9MTByBlOt_QsDhgOf0PvmiETAvKwP-ywhippiSs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);